import { createClient } from '@biltme/backend';

/**
 * bilt-cloud client. Story text, art and narration are generated by the
 * project's own backend functions, so this is the only backend the app talks to.
 */
const url = process.env.EXPO_PUBLIC_BILT_URL ?? '';
const anonKey = process.env.EXPO_PUBLIC_BILT_ANON_KEY ?? '';

export const isBackendConfigured = url.length > 0 && anonKey.length > 0;

export const bilt = createClient(
  isBackendConfigured ? url : 'https://backend-not-configured.invalid',
  isBackendConfigured ? anonKey : 'anon',
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  },
);
